### PR TITLE
Cross-build for aarch64/glibc

### PR DESCRIPTION
**Pull request by hillu**

### CODE REVIEW

**Comment by CroneKorkN** [comment]
Yes, please! ❤️

**Comment by phosei** [comment]
That would be great. 🙏  We have a bunch of Raspberry Pis running Laurel and pre-compiled binaries would make our life much easier. 🙏

**Comment by hillu** [comment]
@phosei I have just added workflows that cross-build for armv7 and aarch64 and upload the resulting binaries as artifacts, see https://github.com/threathunters-io/laurel/actions/runs/9143830699 . Can you give me feedback if those binaries actually work?

**Comment by hillu** [comment]
Never mind. I have added armv7 and aarch64 builds to the 0.6.2 release. Please reopen #180 if you see problems with those.

**Comment by phosei** [comment]
Works in a quick test, thank you!

**Pull request merged**
